import { createActions } from "redux-actions";

export const companyTypes = {
//公司列表
COMPANYWEBLIST:"COMPANYWEBLIST",
COMPANYWEBLIST_SUCCESS:"COMPANYWEBLIST_SUCCESS",
//公司详情
COMPANYDETAILWEB:"COMPANYDETAILWEB",
COMPANYDETAILWEB_SUCCESS:"COMPANYDETAILWEB_SUCCESS",
//公司操作-基本信息,对接人信息
GETBASICCOMPANY:"GETBASICCOMPANY",
GETBASICCOMPANY_SUCCESS:"GETBASICCOMPANY_SUCCESS",
//公司操作记录
GETCOMPANYOPERATERECORD:"GETCOMPANYOPERATERECORD",
GETCOMPANYOPERATERECORD_SUCCESS:"GETCOMPANYOPERATERECORD_SUCCESS",
//头部返回信息
COMPANYOPERATEDETAIL:"COMPANYOPERATEDETAIL",
COMPANYOPERATEDETAIL_SUCCESS:"COMPANYOPERATEDETAIL_SUCCESS",
//审核通过
COMPANYOPERATEPASS:"COMPANYOPERATEPASS",
COMPANYOPERATEPASS_SUCCESS:"COMPANYOPERATEPASS_SUCCESS",
//审核不通过
COMPANYOPERATENOPASS:"COMPANYOPERATENOPASS",
COMPANYOPERATENOPASS_SUCCESS:"COMPANYOPERATENOPASS_SUCCESS",
//资料补全信息
GETCOMPLETEDATA:"GETCOMPLETEDATA",
GETCOMPLETEDATA_SUCCESS:"GETCOMPLETEDATA_SUCCESS",
//复审-通过
COMPANYREVIEWOPERATEPASS:"COMPANYREVIEWOPERATEPASS",
COMPANYREVIEWOPERATEPASS_SUCCESS:"COMPANYREVIEWOPERATEPASS_SUCCESS",
//复审-不通过
COMPANYREVIEWOPERATENOPASS:"COMPANYREVIEWOPERATENOPASS",
COMPANYREVIEWOPERATENOPASS_SUCCESS:"COMPANYREVIEWOPERATENOPASS_SUCCESS"


};

export default createActions({
[companyTypes.COMPANYWEBLIST]: data=> ({data}),
[companyTypes.COMPANYDETAILWEB]: data=> ({data}),
[companyTypes.GETBASICCOMPANY]: data=> ({data}),
[companyTypes.GETCOMPANYOPERATERECORD]: data=> ({data}),
[companyTypes.COMPANYOPERATEDETAIL]: data=> ({data}),
[companyTypes.COMPANYOPERATEPASS]: data=> ({data}),
[companyTypes.COMPANYOPERATENOPASS]: data=> ({data}),
[companyTypes.GETCOMPLETEDATA]: data=> ({data}),
[companyTypes.COMPANYREVIEWOPERATEPASS]: data=> ({data}),
[companyTypes.COMPANYREVIEWOPERATENOPASS]: data=> ({data}),
});

