import { createActions } from "redux-actions";

export const companyTypes = {
//公司列表
COMPANYWEBLIST:"COMPANYWEBLIST",
COMPANYWEBLIST_SUCCESS:"COMPANYWEBLIST_SUCCESS",
//公司详情
COMPANYDETAILWEB:"COMPANYDETAILWEB",
COMPANYDETAILWEB_SUCCESS:"COMPANYDETAILWEB_SUCCESS",
//公司操作-基本信息,对接人信息
GETBASICCOMPANY:"GETBASICCOMPANY",
GETBASICCOMPANY_SUCCESS:"GETBASICCOMPANY_SUCCESS",
//公司操作记录
GETCOMPANYOPERATERECORD:"GETCOMPANYOPERATERECORD",
GETCOMPANYOPERATERECORD_SUCCESS:"GETCOMPANYOPERATERECORD_SUCCESS",
//头部返回信息
COMPANYOPERATEDETAIL:"COMPANYOPERATEDETAIL",
COMPANYOPERATEDETAIL_SUCCESS:"COMPANYOPERATEDETAIL_SUCCESS",
//审核通过
COMPANYOPERATEPASS:"COMPANYOPERATEPASS",
COMPANYOPERATEPASS_SUCCESS:"COMPANYOPERATEPASS_SUCCESS",
//审核不通过
COMPANYOPERATENOPASS:"COMPANYOPERATENOPASS",
COMPANYOPERATENOPASS_SUCCESS:"COMPANYOPERATENOPASS_SUCCESS",
//资料补全信息
GETCOMPLETEDATA:"GETCOMPLETEDATA",
GETCOMPLETEDATA_SUCCESS:"GETCOMPLETEDATA_SUCCESS",
//复审-通过
COMPANYREVIEWOPERATEPASS:"COMPANYREVIEWOPERATEPASS",
COMPANYREVIEWOPERATEPASS_SUCCESS:"COMPANYREVIEWOPERATEPASS_SUCCESS",
//复审-不通过
COMPANYREVIEWOPERATENOPASS:"COMPANYREVIEWOPERATENOPASS",
COMPANYREVIEWOPERATENOPASS_SUCCESS:"COMPANYREVIEWOPERATENOPASS_SUCCESS",
//设立
COMPANYOPERATEESTABLISH:"COMPANYOPERATEESTABLISH",
COMPANYOPERATEESTABLISH_SUCCESS:"COMPANYOPERATEESTABLISH_SUCCESS",
//驳回
COMPANYOPERATEREJECT:"COMPANYOPERATEREJECT",
COMPANYOPERATEREJECT_SUCCESS:"COMPANYOPERATEREJECT_SUCCESS",
//锁定
COMPANYOPERATEBILLLOCK:"COMPANYOPERATEBILLLOCK",
COMPANYOPERATEBILLLOCK_SUCCESS:"COMPANYOPERATEBILLLOCK_SUCCESS",
//发消息给客户
SENDNOTICE:"SENDNOTICE",
SENDNOTICE_SUCCESS:"SENDNOTICE_SUCCESS",
//修改对接人信息
UPDATEDOCK:"UPDATEDOCK",
UPDATEDOCK_SUCCESS:"UPDATEDOCK_SUCCESS",

//省市区
GETREGIONBYPID:"GETREGIONBYPID",
GETREGIONBYPID_SUCCESS:"GETREGIONBYPID_SUCCESS",

SGETREGIONBYPID:"SGETREGIONBYPID",
SGETREGIONBYPID_SUCCESS:"SGETREGIONBYPID_SUCCESS",

QGETREGIONBYPID:"QGETREGIONBYPID",
QGETREGIONBYPID_SUCCESS:"QGETREGIONBYPID_SUCCESS",
//法人库列表
LEGALLIST:"LEGALLIST",
LEGALLIST_SUCCESS:"LEGALLIST_SUCCESS",
//法人详情
LEGALDETAIL:"LEGALDETAIL",
LEGALDETAIL_SUCCESS:"LEGALDETAIL_SUCCESS",
// 法人详情下的公司;列表
GETCOMPANYBYLEGALID:"GETCOMPANYBYLEGALID",
GETCOMPANYBYLEGALID_SUCCESS:"GETCOMPANYBYLEGALID_SUCCESS",
//锁定法人
LOCKLEGAL:"LOCKLEGAL",
LOCKLEGAL_SUCCESS:"LOCKLEGAL_SUCCESS"






};

export default createActions({
[companyTypes.COMPANYWEBLIST]: data=> ({data}),
[companyTypes.COMPANYDETAILWEB]: data=> ({data}),
[companyTypes.GETBASICCOMPANY]: data=> ({data}),
[companyTypes.GETCOMPANYOPERATERECORD]: data=> ({data}),
[companyTypes.COMPANYOPERATEDETAIL]: data=> ({data}),
[companyTypes.COMPANYOPERATEPASS]: data=> ({data}),
[companyTypes.COMPANYOPERATENOPASS]: data=> ({data}),
[companyTypes.GETCOMPLETEDATA]: data=> ({data}),
[companyTypes.COMPANYREVIEWOPERATEPASS]: data=> ({data}),
[companyTypes.COMPANYREVIEWOPERATENOPASS]: data=> ({data}),
[companyTypes.COMPANYOPERATEESTABLISH]: data=> ({data}),
[companyTypes.COMPANYOPERATEREJECT]: data=> ({data}),
[companyTypes.COMPANYOPERATEBILLLOCK]: data=> ({data}),
[companyTypes.SENDNOTICE]: data=> ({data}),
[companyTypes.UPDATEDOCK]: data=> ({data}),
[companyTypes.GETREGIONBYPID]: data=> ({data}),
[companyTypes.SGETREGIONBYPID]: data=> ({data}),
[companyTypes.QGETREGIONBYPID]: data=> ({data}),
[companyTypes.LEGALLIST]: data=> ({data}),
[companyTypes.LEGALDETAIL]: data=> ({data}),
[companyTypes.GETCOMPANYBYLEGALID]: data=> ({data}),
[companyTypes.LOCKLEGAL]: data=> ({data}),
});

